### ISSUE TITLE
Figure not showing up in ?'argoFloats-package'

### ISSUE THREAD

**Issue by j-harbin** [dankelley/argoFloats#64] opened 2020-04-15 12:12 UTC
When I type `?'argoFloats-package'` I receive the following, which does not let me view the work flow figure.

![figure](https://user-images.githubusercontent.com/58750538/79335851-1acfbd80-7ef9-11ea-8071-e746bfc8602e.png)

**Comment by dankelley** [comment] 2020-04-15 12:21
Can you try
```R
library(oce)
?moonAngle
```
and scroll down until you get to "Alternate" to see if you get like below?  This will tell me whether I've done something different, in how I set up the figure.  (I maybe forgot to put a rule in the `.Rbuildignore` file to let this image pass through the file-discarding filter.)

Of course, if they are both not showing images, some more detective work will be required.  Maybe this is only an mswindows thing, for example ... @richardsc has linux and could maybe test that hypothesis.

<img width="618" alt="Screen Shot 2020-04-15 at 9 17 56 AM" src="https://user-images.githubusercontent.com/99469/79336439-1fe13c80-7efa-11ea-98a6-55367afa5b69.png">

**Comment by j-harbin** [comment] 2020-04-15 12:24
Interesting, I do not see that image. Instead, I see the following:
![figure2](https://user-images.githubusercontent.com/58750538/79336892-e826c480-7efa-11ea-90d7-d7f5794000c8.png)

**Comment by dankelley** [comment] 2020-04-15 12:25
@richardsc do you see the image if you do `help("moonAngle",package="oce")` in linux?

**Comment by richardsc** [comment] 2020-04-15 13:46
Hm. I almost never use RStudio, even on Linux. The way I mostly use R is through a terminal (plain text) or through Emacs/ESS, which is also plain text. I can confirm that images do not show up in the help pages that way, though I think there's a way to specify that you want the html version of the help in which case it should pop open a browser.

However, on my windows machine, with RStudio, I *do* see the image:
![image](https://user-images.githubusercontent.com/233584/79344577-650b6b80-7f06-11ea-9a37-6bc1d150884b.png)

**Comment by j-harbin** [comment] 2020-04-15 16:16
Interesting. I rebooted my RStudio and still do not see the image.

**Comment by j-harbin** [comment] 2020-04-15 17:41
Update: I now see the image within `?argoFloats-package` , however, still not for the oce package. Weird!

**Comment by dankelley** [comment] 2020-04-15 17:47
I've not changed anything, so I think the variation in behaviour is something to do with your computer setup.

How this can work in one package and not another is a mystery.

Still, I'd be inclined to suggest closing this issue, since it seems to be something isolated to a single machine.

**Closed** 2020-04-15 17:48 UTC
